### ISSUE TITLE
Quitar js, css y acciones de barra de progreso

### ISSUE THREAD

**Issue by imcamilo** [IMCamilo/compite#3]
Quitar esa barra de progreso. @cepardov

**Comment by cepardov** [comment]
Hay que tomar la decisión en grupo sobre la barra ya que le entrega un aspecto de mas dinamismo

**Comment by imcamilo** [comment]
Un aspecto de mas dinamismo significa nada, @cepardov enfocate en aspectos funcionales del sistema, no en chiches como "dar un aspecto de mas dinamismo"
